# Build stage
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy source code
COPY . .


# Set environment variables
ARG VITE_APP_PORTFOLIO_DOMAIN_NAME
ARG NODE_ENV
ARG VITE_APP_ADMIN_NAME
ARG VITE_APP_ADMIN_EMAIL_ADDRESS
ARG VITE_APP_PUBLIC_KEY
ARG VITE_APP_EMAILJS_SERVICE_ID
ARG VITE_APP_EMAILJS_TEMPLATE_ID

ENV VITE_APP_PORTFOLIO_DOMAIN_NAME=${VITE_APP_PORTFOLIO_DOMAIN_NAME}
ENV NODE_ENV=${NODE_ENV}
ENV VITE_APP_ADMIN_NAME=${VITE_APP_ADMIN_NAME}
ENV VITE_APP_ADMIN_EMAIL_ADDRESS=${VITE_APP_ADMIN_EMAIL_ADDRESS}
ENV VITE_APP_PUBLIC_KEY=${VITE_APP_PUBLIC_KEY}
ENV VITE_APP_EMAILJS_SERVICE_ID=${VITE_APP_EMAILJS_SERVICE_ID}
ENV VITE_APP_EMAILJS_TEMPLATE_ID=${VITE_APP_EMAILJS_TEMPLATE_ID}

# Build the application
RUN npm run build

FROM nginx:alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 35000

CMD ["nginx", "-g", "daemon off;"]
